services:
  - type: web
    name: noc-monitoreo
    runtime: python
    plan: free
    buildCommand: bash build.sh
    startCommand: bash start.sh
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.2
      - key: TZ
        value: America/Lima
